language: python
python:
  - '3.6'
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.7'
before_install:
  - sudo apt-get update -qq
#  Using pip to install instead of setup.py for now to fix numba issue.
#install: python setup.py install
dist: xenial
sudo: true
install: pip install .
script: pytest
stages:
  - name: after_success
    if: env(python) = "3.6"
after_success:
  - pip install sphinx sphinx-gallery sphinx-rtd-theme numpydoc wget pysptools cvxopt
  - sphinx-build -b html -aET docs docs/_build/html
  - touch docs/_build/html/.nojekyll
before_deploy:
  - python setup.py sdist
  - python setup.py bdist_wheel
deploy:
# Github pages deployment
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUBTOKEN
    local_dir: docs/_build/html
    on:
      branch: master
      python: 3.6
# Github releases deployment
  - provider: releases
    skip_cleanup: true
    api_key: $GITHUBTOKEN
    file_glob: true
    file: dist/*
    on:
      tags: true
      branch: master
# PyPi deployment
  - provider: pypi
    skip_cleanup: true
    user:
      secure: $PYPIUSER
    password:
      secure: $PYPIPASS
    distributions: "sdist bdist_wheel"
    file_glob: true
    file:
      - dist/*.whl
      - dist/*.tar.gz
    on:
      tags: true
      branch: master
      python: 3.6
